image:
  name: python:3-slim

definitions:
  steps:
    - step: &install-test
        name: Install and Test
        script:
          - apt-get update && apt-get install git curl unzip -y
          - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip
          - unzip terraform.zip
          - mv terraform /usr/local/bin/
          - chmod +x /usr/local/bin/terraform
          - pip install -r requirements.txt
          - pip install .
          - terradog --version
          - pycodestyle
          - pytest
    - step: &docker-build
        name: Build Docker image
        script:
          - docker build . -t terradog:${BITBUCKET_COMMIT}
        services:
          - docker

pipelines:
  pull-requests:
    "**":
      - step: *install-test
      - step: *docker-build

  branches:
    master:
      - step: *install-test
      - step: *docker-build
